### ISSUE TITLE
Add New Languages

### ISSUE THREAD

**Issue by melikechan** [ubilo-platform/judger#15]
Add languages listed below's compilers/interpreters to the judger options:
- [x] C++20
- [x] C# (both .NET and Mono) (Added with #21)
- [x] Java (both 8 and 21) (Added with https://github.com/ubilo-platform/judgers/commit/6e5e89738bd6a1271fbf8c4db5f806e6d4d40206)
- [x] Rust (Added with #19)
- [x] Node.js (Added with #23)
- [x] Kotlin

**Comment by melikechan** [comment]
I am thinking of postponing Kotlin, it can be added later.
