### ISSUE TITLE
Phase 3 of Adding New Languages

### ISSUE THREAD

**Issue by melikechan** [ubilo-platform/judger#29]
As #26 also mentions adding new languages, I decided to open the issue as "Phase 3".

This issue is not **very important** and, therefore can be worked on later.

Add languages listed below's compilers/interpreters to the judger options:

- [x] Haskell (done by #38, however MLE test doesn't work)
- [x] Scala (done by #58)
- [x] PHP (done by #37)

**Comment by melikechan** [comment]
Elixir and Crystal won't be added.

**Comment by melikechan** [comment]
Scala is added to the dependency installer script, however, it has not been tested yet.

**Comment by melikechan** [comment]
It seems like all I need is to change the commands of Scala runner.

**Comment by melikechan** [comment]
> Elixir and Crystal won't be added.

I have added Elixir in #59 without a lot of work.
