### ISSUE TITLE
Phase 4 of Adding New Languages

### ISSUE THREAD

**Issue by melikechan** [ubilo-platform/judger#30]
As #29 also mentions adding new languages, I decided to open the issue as "Phase 4".

This issue is not **very important** and, therefore can be worked on later.
From now on, other languages will be added **if you ask**. 

Add languages listed below's compilers/interpreters to the judger options:
- [x] Assembly (x86-64) (done by #60) 
- [x] Perl (done by #61)
- [x] Pascal (done by #64)
- [x] Fortran (done by #65)
- [x] Crystal (done by #65) 
- [x] COBOL (done by #63)
- [x] Erlang
- [x] Lua (maybe)
- [x] OCaml
